---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: whalesay
spec:
  backoffLimit: 6
  completions: 10
  template:
    spec:
      containers:
      - image: docker/whalesay
        name: whalesay
        command: ["/bin/sh","-c","cowsay I am going to ace CKAD!"]
      restartPolicy: Never