# Ingress resource
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
spec:
  rules:
   -  host: ckad-mock-exam-solution.com
      http:
        paths:
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: my-video-service
                port:
                  number: 8080

