---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  jobTemplate:
    metadata:
      name: dice
    spec:
      backoffLimit: 25
      ttlSecondsAfterFinished: 20
      completions: 6
      template:
        metadata:
          name: throw-dice-pod
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: throw-dice
          restartPolicy: Never
  schedule: 1 * * * *