
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  accessModes: ["ReadWriteMany"]
  capacity: 
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: /opt/volume/nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: log-claim
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
  volumeName: log-volume

---
kind: Pod
apiVersion: v1
metadata:
  name: logger
spec:
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-claim
  containers:
    - image: nginx:alpine
      name: logger
      volumeMounts:
        - name: log-volume
          mountPath: /var/www/nginx

