---
kind: Namespace
apiVersion: v1
metadata:
  name: dvl1987

---
apiVersion: v1
metadata:
  name: time-config
  namespace: dvl1987
kind: ConfigMap
data:
  TIME_FREQ: "10"

---
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
apiVersion: v1
spec:
  containers:
    - name: time-check
      image: busybox
      command: [ '/bin/sh','-c','while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log' ]
      volumeMounts:
        - name: log
          mountPath:  /opt/time/
      envFrom:
        - configMapRef:
             name: time-config
  volumes:
    - name: log
      emptyDir: {}
