kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-webapp
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: secure-pod
  policyTypes:
    - Ingress
  ingress:
    - from: 
      - podSelector:
           matchLabels:
            name: webapp-color
      ports:
        - port: 80
          protocol: TCP
